### PR TITLE
Add E2E test cases and execute with GH workflow

### PR DESCRIPTION
**Pull request by martinkennelly**
Test cases are simple and check that:
* IPs are unique
* Number of IP pool allocations reflect number of Pod IPs
allocated
* No stale allocations in IP pool following testing

Signed-off-by: Martin Kennelly <mkennell@redhat.com>

### CODE REVIEW

**Review by maiqueb — COMMENTED** [review]
While this addresses a huge gap in whereabouts, I don't think bash is a good choice for implementing the e2e tests.

Do we agree it would be preferable to have it on golang ? 

I don't having this in as is, and port these test cases to a proper programming language afterwards.

**Comment by martinkennelly** [comment]
> Do we agree it would be preferable to have it on golang ?

100%

yeah - you're totally right it would be so much nicer in golang. I wanted to sleep at night with the changes I am currently making in the other PRs, so I setup this.

I think the setting up in the infra with KinD is nice to keep and would be used by golang test implementation. I believe @nicklesimba  is working on golang tests and can use that and discard the test shell scripts here.

**Comment by maiqueb** [comment]
> > Do we agree it would be preferable to have it on golang ?
> 
> 100%
> 
> yeah - you're totally right it would be so much nicer in golang. I wanted to sleep at night with the changes I am currently making in the other PRs, so I setup this.
> 
> I think the setting up in the infra with KinD is nice to keep and would be used by golang test implementation. 

Absolutely.

> I believe @nicklesimba is working on golang tests and can use that and discard the test shell scripts here.

Didn't know; nice. I can collaborate on that as well, if needed.

**Comment by dougbtv** [comment]
I'm OK with proceeding with having these as a "version 1", and then we'll come back as a second pass, and have @nicklesimba work through converting into golang-based tests. 

I think that while the bash tests aren't ideal, they are pragmatic to get some tests in place for the short run. That being said, I'm OK to approve and then follow-up, when we come out of WIP

**Comment by dougbtv** [comment]
Giving this a CI re-run after merging #142 :+1:

**Comment by martinkennelly** [comment]
Forced pushed to change multus deployment path.

**Pull request merged**
