### PR TITLE
Bump Go version to `1.19`

### PR DESCRIPTION
**Pull request by pjbgf**
**What this PR does / why we need it**:

Bumps Go version to `1.19` and removes usage of package `io/ioutil` which is deprecated since Go `1.16`.

Supersedes https://github.com/k8snetworkplumbingwg/whereabouts/pull/271.

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
Thanks. Will merge once golang 1.18 goes EOL.

**Comment by maiqueb** [comment]
Seems you need to also bump the code generators @pjbgf .
https://github.com/k8snetworkplumbingwg/whereabouts/actions/runs/3940430333/jobs/6741685662

**Comment by pjbgf** [comment]
@maiqueb thanks for pointing it out, I updated `zz_generated.deepcopy.go` and also made sure that the boilerplate across the generated files were also updated.

**Comment by maiqueb** [comment]
Oh man, sorry, but your code was mistakenly merged as part of #297 ... 

I hope you do get the contribution stats. 
@pjbgf

**Comment by nicklesimba** [comment]
@pjbgf Hey, apologies that we didn't get your PR merged -- probably should have gotten your PR merged first. Your commits have made it into master branch however. I'll close out this PR. I appreciate your contribution!

**Comment by pjbgf** [comment]
@maiqueb @nicklesimba no worries, thank you for the heads up. :thumbsup:

**Pull request closed without merging**
