### PR TITLE
Add support for CNI version

### PR DESCRIPTION
**Pull request by antoninbas**
The hack/build-go.sh script is modified to pass version information
during the build through LDFLAGS, which is a pretty standard technique.

This information can then be used to report the version of the
whereabouts CNI plugin at runtime; before this change the plugin would
just print "TODO".

### CODE REVIEW

**Comment by antoninbas** [comment]
example:
```bash
abas-a01:whereabouts abas$ ./hack/build-go.sh
VERSION: v0.4.2
GIT_SHA: 6f75b4f
GIT_TREE_STATE: clean
RELEASE_STATUS: unreleased
abas-a01:whereabouts abas$ ./bin/whereabouts
whereabouts v0.4.2-6f75b4f darwin/amd64
abas-a01:whereabouts abas$
```

**Comment by antoninbas** [comment]
Could I get a review on this? Happy to make changes if there is feedback.

**Comment by dougbtv** [comment]
Sorry for the delays! Some reviews have gotten lost in the shuffle with some of the ongoing work for Whereabouts related to race conditions and optimization at scale -- this does look really good.

**Review by dougbtv — APPROVED** [review]
LGTM!

**Pull request merged**
