### PR TITLE
Update containernetworking deps

### PR DESCRIPTION
**Pull request by manuelbuil**
**What this PR does / why we need it**:

This PR updates to a newer version:
* github.com/containernetworking/plugins
* github.com/containernetworking/cni

There are a few changes that need to happen to start using the new versions:
* Start using github.com/containernetworking/cni/pkg/types/040 instead of "current" because the latter does not exist anymore. Once this PR is merged, I'll work on another PR to migrate from 040 type to 100.
* types020.SupportedVersions cannot be used anymore. Instead, I explicitely added the three values: """, "0.1.0", "0.2.0"

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
No issue. Should I create an issue?

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
You must make peace with the linter; other than that, good to go.
Thanks.

**Comment by manuelbuil** [comment]
> You must make peace with the linter; other than that, good to go. Thanks.

Isn't the linter part of the CI?

**Comment by maiqueb** [comment]
> > You must make peace with the linter; other than that, good to go. Thanks.
> 
> Isn't the linter part of the CI?

It is, I just checked this before seeing the CI results. 

If you check the files changed tab you'll see the linter throws warnings in some files you've updated.

Still, warnings != errors.

**Comment by manuelbuil** [comment]
> > > You must make peace with the linter; other than that, good to go. Thanks.
> > 
> > 
> > Isn't the linter part of the CI?
> 
> It is, I just checked this before seeing the CI results.
> 
> If you check the files changed tab you'll see the linter throws warnings in some files you've updated.
> 
> Still, warnings != errors.

Thanks, I did not see that. The lint warning is `should have a package comment` for `package main` and `package config`, which happens to be the files I changed. I can add one liner for each so that we don't see it again

**Pull request merged**
